import {
  Dumbbell,
  Flame,
  Flower,
  DoorOpen,
  Users,
  Martini,
  Sliders,
  Bath,
  Car,
  Wifi,
  Shield,
  Camera,
  TreePine,
  Waves,
  Coffee,
  Utensils,
  ShoppingBag,
  School,
  Train,
  MapPin,
  Clock,
  Phone,
  Mail,
  MessageSquare,
  Building2,
  Home,
  Layout,
  FileText,
  Info,
  BarChart2,
  Maximize2,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Search,
  CheckCircle,
  Download,
  BadgeDollarSign,
  MapPinned,
  Trees,
  ShoppingCart,
  Calendar,
  LucideIcon
} from "lucide-react"

export interface Facility {
  name: string
  icon: LucideIcon
}

export const facilities: Facility[] = [
  { name: "Swimming Pool", icon: Waves },
  { name: "Gymnasium", icon: Dumbbell },
  { name: "BBQ Area", icon: Flame },
  { name: "Garden", icon: Flower },
  { name: "Lobby", icon: DoorOpen },
  { name: "Function Room", icon: Users },
  { name: "Sky Lounge", icon: Martini },
  { name: "Study Room", icon: Sliders },
  { name: "Jacuzzi", icon: Bath },
  { name: "Car Park", icon: Car },
  { name: "WiFi", icon: Wifi },
  { name: "Security", icon: Shield },
  { name: "CCTV", icon: Camera },
  { name: "Landscaping", icon: TreePine },
  { name: "Café", icon: Coffee },
  { name: "Restaurant", icon: Utensils },
  { name: "Retail", icon: ShoppingBag },
  { name: "Childcare", icon: School },
  { name: "MRT Access", icon: Train },
  { name: "Location", icon: MapPin },
  { name: "24/7 Concierge", icon: Clock },
  { name: "Phone", icon: Phone },
  { name: "Email", icon: Mail },
  { name: "WhatsApp", icon: MessageSquare },
  { name: "Building", icon: Building2 },
  { name: "Home", icon: Home },
  { name: "Layout", icon: Layout },
  { name: "Documents", icon: FileText },
  { name: "Information", icon: Info },
  { name: "Analytics", icon: BarChart2 },
  { name: "Fullscreen", icon: Maximize2 },
  { name: "Navigation", icon: ChevronLeft },
  { name: "Next", icon: ChevronRight },
  { name: "Up", icon: ChevronUp },
  { name: "Down", icon: ChevronDown },
  { name: "Search", icon: Search },
  { name: "Success", icon: CheckCircle },
  { name: "Download", icon: Download },
  { name: "Pricing", icon: BadgeDollarSign },
  { name: "Map", icon: MapPinned },
  { name: "Nature", icon: Trees },
  { name: "Shopping", icon: ShoppingCart },
  { name: "Events", icon: Calendar }
]
